spring.application.name=configurator-api
server.port=8080

sap.api.base-url=https://sandbox.api.sap.com/cpservices/prodconf
sap.api.key=3W8L2uo2AHy9QNVaMA9oYdO2TK0qU4rl
sap.api.kb-id=80
sap.api.product-key=CPS_BURGER